FROM python:3.10-slim

WORKDIR /app

# Set entrypoint
ENTRYPOINT ["python"]

# Set command
CMD ["app.py", "--debug"]

# Shell form
RUN echo "Hello, World!"

# Exec form
RUN ["echo", "Hello, World!"]

EXPOSE 8000 